### ISSUE TITLE
there should be a separate downloads page on the website

### ISSUE THREAD

**Issue by pacharanero** [NHSbuntu/www.nhsbuntu.org#26]
1. some people don't like links to big files shared directly in eg Twitter due to security concerns - 'where am I being sent? what am I downloading here? (they also often don't work because the https://t.co/<something> address that twitter links have don't appear to resolve until the download is finished)

1. we now have at least 2 'editions' ( x64, x32) and it's likely to be more soon (ARM, 'stable/release-candidate/nightly etc for all of those editions), and maybe even different desktop environments...

So, having a downloads page would be nice as it give us a page link for use case 1. and a place to list and explain all the versions in 2. as well as MD5 hashes.

It would be good if we could make the links and MD5s automatically updated, so that there is no maintenance burden and it's always up to date. @robdyke you automated the linking to latest ISO, could you let me know how you did this. I'm happy to create the actual page

**Comment by robdyke** [comment]
See this snippet

https://github.com/NHSbuntu/www.nhsbuntu.org/blob/master/_includes/downloadiso.html

**Comment by robdyke** [comment]
Resolved in NHoS.
