### ISSUE TITLE
Link to github 

### ISSUE THREAD

**Issue by robdyke** [NHSbuntu/www.nhsbuntu.org#9]
Octocat icon and link to github repo(s)

**Comment by robdyke** [comment]
Whoops. PR #16 puts github ribbon over mobile menu.

**Comment by pacharanero** [comment]
but the mobile nav still works though :-)

**Comment by robdyke** [comment]
![selection_347](https://cloud.githubusercontent.com/assets/941696/25489346/6fae97d4-2b61-11e7-99eb-f72110ec6b4b.png)

**Comment by robdyke** [comment]
Closing. Thanks @pacharanero
